name: Torque 3D
root: https://torque3d.org
permalink: /:category/:title
markdown: kramdown
wikiroot: https://wiki.torque3d.org
forumsroot: https://forums.torque3d.org
github: TorqueGameEngines/Torque3D